
services:
  database:
    build:
      context: ./DataBase
      dockerfile: Dockerfile
    environment:
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/setup_complete"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@database:1521:xe
      - SPRING_DATASOURCE_USERNAME=DOSI
      - SPRING_DATASOURCE_PASSWORD=DOSI
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://backend:8082/etu || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 15s

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  oracle-data:
