-- 
-- Projet SIGOTI - CSCI_STA
-- 	Script de suppression des vues
-- 	Ph. Saliou - 10 octobre 2012 - 
-- 

DROP VIEW V_CODE_NOTE;
DROP VIEW V_ETAT_CONVENTION;
DROP VIEW V_ETAT_EVALUATION_ENTREPRISE;
DROP VIEW V_ETAT_OFFRE;
DROP VIEW V_ETAT_STAGE;
DROP VIEW V_ETAT_STRUCTURE_EVAL;
DROP VIEW V_INTERLOCUTEUR;
DROP VIEW V_NIVEAU_REQUIS;
DROP VIEW V_SALLE;
DROP VIEW V_TYPE_CONTACT;
