--
-- Projet SIGOTI - CSCI_STA
-- 	Script de suppression des tables
-- 	Ph. Saliou - 10 octobre 2012 -
--

DROP TABLE NOTE_ENTREPRISE;
DROP TABLE CODE_NOTATION;
DROP TABLE NOTATION_STAGE;
DROP TABLE CRITERE_ENTREPRISE;
DROP TABLE STRUCTURE_EVALUATION;
DROP TABLE EVALUATION_ENTREPRISE;
DROP TABLE AVENANT;
DROP TABLE VISITE_STAGE;
DROP TABLE CONTACT_STAGE;
DROP TABLE STAGE;
DROP TABLE SOUTENANCE;
DROP TABLE OFFRE_STAGE;


