-- 
-- Script de création DDL du CSCI-ADM
-- Ph. Saliou - 04 octobre 2012 - 
--	

PROMPT Creating Foreign Key on 'ETUDIANT'
ALTER TABLE ETUDIANT ADD (CONSTRAINT
 ETU_PRO_FK FOREIGN KEY 
  (ANNEE_PRO) REFERENCES PROMOTION
  (ANNEE_PRO))
/

PROMPT Creating Foreign Key on 'EMPLOYE'
ALTER TABLE EMPLOYE ADD (CONSTRAINT
 EMP_ENT_FK FOREIGN KEY 
  (NO_ENTREPRISE) REFERENCES ENTREPRISE
  (NO_ENTREPRISE))
/

PROMPT Creating Foreign Key on 'EMPLOYE'
ALTER TABLE EMPLOYE ADD (CONSTRAINT
 EMP_DIP_FK FOREIGN KEY 
  (NO_ETUDIANT_NAT) REFERENCES DIPLOME
  (NO_ETUDIANT_NAT))
/

PROMPT Creating Foreign Key on 'POSTE_ENTREPRISE'
ALTER TABLE POSTE_ENTREPRISE ADD (CONSTRAINT
 POE_DIP_FK FOREIGN KEY 
  (NO_ETUDIANT_NAT) REFERENCES DIPLOME
  (NO_ETUDIANT_NAT))
/

PROMPT Creating Foreign Key on 'POSTE_ENTREPRISE'
ALTER TABLE POSTE_ENTREPRISE ADD (CONSTRAINT
 POE_ENT_FK FOREIGN KEY 
  (NO_ENTREPRISE) REFERENCES ENTREPRISE
  (NO_ENTREPRISE))
/

PROMPT Creating Foreign Key on 'CANDIDAT'
ALTER TABLE CANDIDAT ADD (CONSTRAINT
 CAN_PRO_FK FOREIGN KEY 
  (ANNEE_PRO) REFERENCES PROMOTION
  (ANNEE_PRO))
/

PROMPT Creating Foreign Key on 'DIPLOME'
ALTER TABLE DIPLOME ADD (CONSTRAINT
 DIP_ETU_FK FOREIGN KEY 
  (NO_ETUDIANT_NAT) REFERENCES ETUDIANT
  (NO_ETUDIANT_NAT))
/


