--
-- Projet SIGOTI - CSCI_STA
-- 	Script de création d'une vue par domaine dynamique
-- 	Ph. Saliou - 10 octobre 2012 - 
--			

PROMPT Creating View 'V_CODE_NOTE'
CREATE OR REPLACE FORCE VIEW V_CODE_NOTE
 (CODE, ABREVIATION,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'CODE_NOTE'
/

PROMPT Creating View 'V_ETAT_CONVENTION'
CREATE OR REPLACE FORCE VIEW V_ETAT_CONVENTION
 (CODE, ABREVIATION,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'ETAT_CONVENTION'
/

PROMPT Creating View 'V_ETAT_EVALUATION_ENTREPRISE'
CREATE OR REPLACE FORCE VIEW V_ETAT_EVALUATION_ENTREPRISE
 (CODE, ABREVIATION,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'ETAT_EVALUATION_ENTREPRISE'
/

PROMPT Creating View 'V_ETAT_OFFRE'
CREATE OR REPLACE FORCE VIEW V_ETAT_OFFRE
 (CODE, ABREVIATION,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'ETAT_OFFRE'
/

PROMPT Creating View 'V_ETAT_STAGE'
CREATE OR REPLACE FORCE VIEW V_ETAT_STAGE
 (CODE, ABREVIATION,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'ETAT_STAGE'
/

PROMPT Creating View 'V_ETAT_STRUCTURE_EVAL'
CREATE OR REPLACE FORCE VIEW V_ETAT_STRUCTURE_EVAL
 (CODE, ABREVIATION,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'ETAT_STRUCTURE_EVAL'
/

PROMPT Creating View 'V_INTERLOCUTEUR'
CREATE OR REPLACE FORCE VIEW V_INTERLOCUTEUR
 (CODE, ABREVIATION,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'INTERLOCUTEUR'
/

PROMPT Creating View 'V_NIVEAU_REQUIS'
CREATE OR REPLACE FORCE VIEW V_NIVEAU_REQUIS
 (CODE, ABREVIATION,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'NIVEAU_REQUIS'
/

PROMPT Creating View 'V_SALLE'
CREATE OR REPLACE FORCE VIEW V_SALLE
 (CODE, ABREVIATION,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'SALLE'
/

PROMPT Creating View 'V_TYPE_CONTACT'
CREATE OR REPLACE FORCE VIEW V_TYPE_CONTACT
 (CODE, ABREVIATION,SIGNIFICATION)
 AS SELECT CGRC.RV_LOW_VALUE CODE
          ,CGRC.RV_ABBREVIATION ABREVIATION
          ,CGRC.RV_MEANING SIGNIFICATION
FROM CG_REF_CODES CGRC
  WHERE CGRC.RV_DOMAIN = 'TYPE_CONTACT'
/

