--
-- Projet SIGOTI - CSCI_STA
-- 	Script de création des clés primaires
-- 	Ph. Saliou - 10 octobre 2012 - 
--
 
PROMPT Creating Primary Key on 'VISITE_STAGE'
ALTER TABLE VISITE_STAGE
 ADD (CONSTRAINT VST_PK PRIMARY KEY 
  (NO_ETUDIANT_NAT
  ,ANNEE_PRO))
/

PROMPT Creating Primary Key on 'AVENANT'
ALTER TABLE AVENANT
 ADD (CONSTRAINT AVE_PK PRIMARY KEY 
  (NO_AVENANT))
/

PROMPT Creating Primary Key on 'CONTACT_STAGE'
ALTER TABLE CONTACT_STAGE
 ADD (CONSTRAINT CTS_PK PRIMARY KEY 
  (NO_ETUDIANT_NAT
  ,ANNEE_PRO
  ,DATE_CONTACT))
/

PROMPT Creating Primary Key on 'STRUCTURE_EVALUATION'
ALTER TABLE STRUCTURE_EVALUATION
 ADD (CONSTRAINT STRE_PK PRIMARY KEY 
  (NO_EVALUATION))
/

PROMPT Creating Primary Key on 'SOUTENANCE'
ALTER TABLE SOUTENANCE
 ADD (CONSTRAINT SOUT_PK PRIMARY KEY 
  (NO_SESSION
  ,ANNEE_PRO))
/

PROMPT Creating Primary Key on 'STAGE'
ALTER TABLE STAGE
 ADD (CONSTRAINT STG_PK PRIMARY KEY 
  (NO_ETUDIANT_NAT
  ,ANNEE_PRO))
/

PROMPT Creating Primary Key on 'NOTE_ENTREPRISE'
ALTER TABLE NOTE_ENTREPRISE
 ADD (CONSTRAINT NOTE_PK PRIMARY KEY 
  (CRITE_ID
  ,NO_ETUDIANT_NAT
  ,ANNEE_PRO))
/

PROMPT Creating Primary Key on 'EVALUATION_ENTREPRISE'
ALTER TABLE EVALUATION_ENTREPRISE
 ADD (CONSTRAINT EVAE_PK PRIMARY KEY 
  (NO_ETUDIANT_NAT
  ,ANNEE_PRO))
/

PROMPT Creating Primary Key on 'CRITERE_ENTREPRISE'
ALTER TABLE CRITERE_ENTREPRISE
 ADD (CONSTRAINT CRITE_PK PRIMARY KEY 
  (CRITE_ID))
/

PROMPT Creating Primary Key on 'OFFRE_STAGE'
ALTER TABLE OFFRE_STAGE
 ADD (CONSTRAINT OFF_PK PRIMARY KEY 
  (NO_OFFRE))
/

PROMPT Creating Primary Key on 'NOTATION_STAGE'
ALTER TABLE NOTATION_STAGE
 ADD (CONSTRAINT NOTS_PK PRIMARY KEY 
  (NO_BAREME))
/

PROMPT Creating Primary Key on 'CODE_NOTATION'
ALTER TABLE CODE_NOTATION
 ADD (CONSTRAINT CODN_PK PRIMARY KEY 
  (CODN_ID))
/

