--
-- Projet SIGOTI - CSCI_STA
-- 	Script de création des séquences
-- 	Ph. Saliou - 10 octobre 2012 - 
--
 
PROMPT Creating Sequence 'NOTS_SEQ'
CREATE SEQUENCE NOTS_SEQ
 START WITH 100
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'OFF_SEQ'
CREATE SEQUENCE OFF_SEQ
 START WITH 100
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'STRE_SEQ'
CREATE SEQUENCE STRE_SEQ
 START WITH 100
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'AVE_SEQ'
CREATE SEQUENCE AVE_SEQ
 START WITH 100
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'CODN_SEQ'
CREATE SEQUENCE CODN_SEQ
 START WITH 100
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'SOUT_SEQ'
CREATE SEQUENCE SOUT_SEQ
 START WITH 100
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Sequence 'CRITE_SEQ'
CREATE SEQUENCE CRITE_SEQ
 START WITH 100
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

