type Etudiant = {
    noEtudiantNat: string;
    anneePro: number;
    codeCom: string;
    noEtudiantUbo: string;
    sexe: 'M' | 'F';  
    nom: string;
    prenom: string;
    dateNaissance: string;  
    lieuNaissance: string;
    situation: string;
    nationalite: string;
    telPort: string;
    telFixe: string;
    email: string;
    actuAdresse: string;
    actuCp: string;
    actuVille: string;
    actuPays: string;
    permAdresse: string;
    permCp: string;
    permVille: string;
    permPays: string;
    dernierDiplome: string;
    universite: string;
    sigleEtu: string;
    compteCri: string;
    uboEmail: string;
    grpeAnglais: string;  
    abandonMotif: string;
    abandonDate: string | null;  
    estDiplome: boolean;
  };
  